version: '3.8'

services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-frontend-dev
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app 

  debug-helper:
    image: busybox 
    
