 # Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Install MongoDB client tools
RUN apt-get update && apt-get install -y mongo-tools

# Bundle app source
COPY . .

# Install nodemon globally
RUN npm install -g nodemon

# Expose the port that your app runs on
EXPOSE 3000

# Start the app with nodemon
CMD ["nodemon", "index.js"]










